networks:
  b2c:
volumes:
  mysql-db:
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=tasks
      - MYSQL_ROOT_PASSWORD=ghi
    networks:
      - b2c
    ports:
      - "8800:3306"
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    build: ./api
    restart: always
    networks:
      - b2c
    ports:
      - 8801:8080
    environment:
      - DATABASE_URL="mysql://root:ghi@127.0.0.1:8800/tasks"
      - PORT=8080
    depends_on:
      - db
